@{values}-----------------------------------------------------------------------
title: Progress
value: 50
total: 100

@{style}----------------------------------------------------------------
$background = #ddd
$border = #ccc
$foreground = #aaa
$text-color = #fff

.progress
  & .bar
    background $background
    border 1px dashed $border
    width 100%
    height 20px
    & .value
      background $foreground
      height 12px
      font-size 11px
      color $text-color
      padding 4px

@{layout}-----------------------------------------------------------------------
.progress
  .title= title
  .bar
    .value(style='width:'+ (value * 1.0 / total) * 100 + '%')= value + "/" + total

@{script}-----------------------------------------------------------------------
math =
  root:   Math.sqrt
  square: square
  cube:   (x) -> x * square x
