@{values}-----------------------------------------------------------------------
title: Progress
value: 50
total: 100

@{style}(stylus)----------------------------------------------------------------
$background = #dddddd

.progress
  background $background
  width 100%
  height 20px
  
@{layout}-----------------------------------------------------------------------
.progress
  .title title
  .bar(style='width:'+ (value * 1.0 / total) * 100 + '%') value

@{script}-----------------------------------------------------------------------
math =
  root:   Math.sqrt
  square: square
  cube:   (x) -> x * square x